### ISSUE TITLE
Help downloading model

### ISSUE THREAD

**Issue by betoshogun** [TheJacksonLaboratory/Digital-Glomerular-identification#1]
Good afternoon,

Could you please share your trained ilastik model? I had trouble downloading from the provided link.

Thanks!

**Comment by susan-sheehan** [comment]
Hi, I would be happy to share, but it is large(~80GB), do you have a globus endpoint?   Dropbox with enough storage I could have access to etc?

~ Sue

**Comment by susan-sheehan** [comment]
I've put a new copy on the ftp server
